// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:99b3ad80-643e-473c-8cd9-9eccbfbd2957",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fg80hW8P0",
    "aws_user_pools_web_client_id": "21gnt1cbdn30lonb6fog0tn76e",
    "aws_appsync_graphqlEndpoint": "https://ngvc6izbcze5rcslccxwdcf2wy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "appsyncchattest56ec641596654c6492877efedca1d002",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
