// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:58071aa9-290a-4c88-9460-732da759f638",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OH19MEsSp",
    "aws_user_pools_web_client_id": "5i16ijmopdb295bvqtfe420aul",
    "aws_appsync_graphqlEndpoint": "https://i7ytsubarfazvpdsiyaib2a3ui.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "appsyncchattest6666bfdb17324c18bbf50d488639de82",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
